# Generated by Django 5.1.6 on 2025-03-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_teacher_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
