# Generated by Django 5.1.6 on 2025-03-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pub_date']},
        ),
    ]
